# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: invoicepdf 0.1.11 ruby lib

Gem::Specification.new do |s|
  s.name = "invoicepdf"
  s.version = "0.1.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["A A"]
  s.date = "2016-07-13"
  s.description = "Easily create PDF invoices"
  s.email = "info@soluvi.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "init.rb",
    "lib/generators/standard.rb",
    "lib/invoice/helpers.rb",
    "lib/invoice/invoice.rb",
    "lib/invoice/line_item.rb",
    "lib/invoicepdf.rb"
  ]
  s.homepage = "http://github.com/Soluvi/invoicepdf"
  s.licenses = ["MIT"]
  s.rubyforge_project = "invoicepdf"
  s.rubygems_version = "2.4.5.1"
  s.summary = "Easily create PDF invoices"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<prawn>, [">= 0"])
      s.add_runtime_dependency(%q<prawn-table>, [">= 0"])
    else
      s.add_dependency(%q<prawn>, [">= 0"])
      s.add_dependency(%q<prawn-table>, [">= 0"])
    end
  else
    s.add_dependency(%q<prawn>, [">= 0"])
    s.add_dependency(%q<prawn-table>, [">= 0"])
  end
end

