# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "invoicepdf"
  s.version = "0.1.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["A A"]
  s.date = "2012-11-06"
  s.description = "Easily create PDF invoices"
  s.email = "axidium@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "init.rb",
    "lib/generators/standard.rb",
    "lib/invoice/helpers.rb",
    "lib/invoice/invoice.rb",
    "lib/invoice/line_item.rb",
    "lib/invoicepdf.rb"
  ]
  s.homepage = "http://github.com/AndreiGorin/invoicepdf"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "invoicepdf"
  s.rubygems_version = "1.8.24"
  s.summary = "Easily create PDF invoices"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<horo>, [">= 0"])
      s.add_runtime_dependency(%q<prawn>, [">= 1.0.0.rc1"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<horo>, [">= 0"])
      s.add_dependency(%q<prawn>, [">= 1.0.0.rc1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<horo>, [">= 0"])
    s.add_dependency(%q<prawn>, [">= 1.0.0.rc1"])
  end
end

